import type {GetServerSideProps, NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Banner} from "../components/banner";
import {NavBar} from "../components/nav"
import {SectionCards} from "../components/card/sectionCards";
import {VideoRequestModel} from "../models";
import {getPopularVideos, getVideos} from "../lib/videos";

export  const getServerSideProps: GetServerSideProps = async (context) => {
    const disneyVideos: VideoRequestModel[] =await getVideos('disney trailer');
    const productivityVideos: VideoRequestModel[]  = await getVideos("Productivity");
    const travelVideos: VideoRequestModel[]  = await getVideos("indie music");
    const popularVideos = await getPopularVideos();
    return {props: {disneyVideos ,productivityVideos,travelVideos,popularVideos}};
}
const Home: NextPage = (props) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Netflix </title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.main}>
                <NavBar props={{
                    userName: "me@me.com"
                }}/>
                <Banner props={
                    {
                        title: "Clifford the red dog1",
                        subTitle: "a very cute dog",
                        imgUrl: "/static/clifford.webp"
                    }}/>
                <div className={styles.sectionWrapper}>
                <SectionCards
                    props={{title: "Disney", videos: props.disneyVideos, size: "large", shouldScale: true, shouldWrap: true}}/>
                    <SectionCards
                        props={{title: "Travel", videos: props.travelVideos, size: "small", shouldScale: true, shouldWrap: true}}/>
                    <SectionCards
                        props={{title: "Productivity", videos: props.productivityVideos, size: "medium", shouldScale: true, shouldWrap: true}}/>
                    <SectionCards
                        props={{title: "Popular", videos: props.popularVideos, size: "small", shouldScale: true, shouldWrap: true}}/>
                </div>
            </div>
        </div>
    )
}

export default Home
