import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Banner} from "../components/banner";
import {NavBar} from "../components/nav"
import {SectionCards} from "../components/card/sectionCards";
import {VideoRequestModel} from "../models";

const Home: NextPage = () => {
    const disneyVideos:VideoRequestModel[]=[
        {id:"1", imgUrl:"/static/clifford.webp"},
        {id:"1", imgUrl:"/static/clifford.webp"},
        {id:"1", imgUrl:"/static/clifford.webp"},
        {id:"1", imgUrl:"/static/clifford.webp"},
        {id:"1", imgUrl:"/static/clifford.webp"},
    ];
    return (
        <div className={styles.container}>
            <Head>
                <title>Netflix </title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.main}>
                <NavBar props={{
                    userName: "me@me.com"
                }}/>
                <Banner props={
                    {
                        title: "Clifford the red dog1",
                        subTitle: "a very cute dog",
                        imgUrl: "/static/clifford.webp"
                    }}/>
                <div className={styles.sectionWrapper}>
                <SectionCards
                    props={{title: "test title 1", videos: disneyVideos, size: "large", shouldScale: true, shouldWrap: true}}/>
                </div>
            </div>
        </div>
    )
}

export default Home
