import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Banner} from "../components/banner";
import {NavBar} from "../components/nav";
import {Card} from "../components/card/card";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Netflix </title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.main}>
                <NavBar props={{
                    userName: "me@me.com"
                }}/>
                <Banner props={
                    {
                        title: "Clifford the red dog1",
                        subTitle: "a very cute dog",
                        imgUrl: "/static/clifford.webp"
                    }}/>


                <Card props={{imgUrl : "/static/clifford.webp",size : "large",id:0,shouldScale : true,}}/>
                <Card props={{imgUrl : "/static/clifford.webp",size : "medium",id:0,shouldScale : true,}}/>
                <Card props={{imgUrl : "/static/clifford.webp",size : "small",id:0,shouldScale : true,}}/>
            </div>
        </div>
    )
}

export default Home
